### ISSUE TITLE
"video download" popup won't disable

### ISSUE THREAD

**Issue by gifthubbro** [subhra74/xdm#278]
I'm using the addon for XDM from [here](https://addons.mozilla.org/en-US/firefox/addon/xdm-browser-monitor/), the problem is every time I click to download a file [this](https://i.imgur.com/hZTCH3t.png) pops up,

**Comment by subhra74** [comment]
It has been already fixed , please follow steps mentioned below:
https://github.com/subhra74/xdm/wiki/Disabling-DOWNLOAD-VIDEO-popup

**Comment by gifthubbro** [comment]
I already had that option [enabled ](https://i.imgur.com/0YyzAeJ.png)but I still get the [popup ](https://i.imgur.com/hZTCH3t.png)when downloading files using the [firefox addon](https://addons.mozilla.org/en-US/firefox/addon/xdm-browser-monitor/)

**Comment by ameaninglessname** [comment]
https://github.com/subhra74/xdm/issues/547#issuecomment-912955875
Same problem here.

**Comment by subhra74** [comment]
Currently I am working on new rewrite of xdm to fix fundamental problems like this. The rewrite will be merged soon to xdm public repo and i am expecting to release beta in October

**Comment by ameaninglessname** [comment]
> 

Sry to bother, but any news with xdm?

**Comment by Enissay** [comment]
@subhra74 Any update please ?
