### ISSUE TITLE
XDM doesnt work after updating Brave Browser

### ISSUE THREAD

**Issue by lightwarriah** [subhra74/xdm#507]
**Describe the bug**
XDM doesn't work after updating Brave Browser (Linux Mint)

**To Reproduce**
XtremeDownloadManager extension (version 2.1) worked well until I updated Brave Browser to version 1.21.73
Now I get an error message that XDM version 7 is required.
I’ve already installed XDM Version 7.2.11 but can’t force them both to cooperate.

Downloading a YT video in XDM by "file => download video" doesn't work either.
(See screenshots and logfile)

**Expected behavior**

**Screenshots**
![XDM YouTube URL](https://user-images.githubusercontent.com/80011287/109887242-a83b0e00-7c81-11eb-90f0-0ba52c3678ee.png)
![XDM YouTube URL Result](https://user-images.githubusercontent.com/80011287/109887256-aec98580-7c81-11eb-9c2d-5b898af631d8.png)

**please complete the following information:**
 - OS: Linux Mint 19.1 Cinnamon, Kernel: 4.15.0-136-generic
 - Brave Browser version 1.21.73 Chromium: 89.0.4389.72 (Offizieller Build) (64-Bit)
 - XDM addon Version 2.1
 - XDM Version 7.2.11 with Java Eclipse OpenJ9 11.0.6 on Linux
 
**Generated log using below method**
[ main ] loading...
[ main ] 11.0.6 4.15.0-136-generic
[ main ] Loading config...
[ main ] Creating folders
[ main ] starting monitoring...
[ main ] Init app
[ main ] Loading fonts
de
[ main ] Loading language de
[ main ] Context initialized
[ Thread-5 ] java.net.BindException: Die Adresse wird bereits verwendet (Bind failed)
	at java.base/java.net.PlainSocketImpl.socketBind(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.bind(Unknown Source)
	at java.base/java.net.ServerSocket.bind(Unknown Source)
	at java.base/java.net.ServerSocket.bind(Unknown Source)
	at xdman.monitoring.BrowserMonitor.run(BrowserMonitor.java:186)
	at java.base/java.lang.Thread.run(Unknown Source)
[ Thread-5 ] instance already runninng

I'm sorry, even though I switched language back to english and closed XDM, the logfile is still in german.

**Additional context**
I also posted a request in the Brave Browser community:
[https://community.brave.com/t/xdm-doesnt-work-after-updating-brave-browser/212260](url)

**Comment by naufalovich** [comment]
Also happen to me. Mine using Linux Mint 20.1

**Comment by lightwarriah** [comment]
Brave Browser support sent me a response:
"...I’ve seen a few extra reports of extensions “breaking” after the latest update and am digging into the cause. ..."

**Comment by Aikatsui** [comment]
This is not a XDM issue,

1. Go to `brave://adblock/`
2. Add following rules to "custom filters" and may help for other affected extensions
```
||localhost^$important,third-party
||127.^$important,third-party
||[::1]^$important,third-party
||192.168.^$important,third-party
@@127.0.0.1
```

**Comment by beatschubser** [comment]
> This is not a XDM issue,
> 
> 1. Go to `brave://adblock/`
> 2. Add following rules to "custom filters" and may help for other affected extensions
> 
> ```
> ||localhost^$important,third-party
> ||127.^$important,third-party
> ||[::1]^$important,third-party
> ||192.168.^$important,third-party
> @@127.0.0.1
> ```
> 
> credits: @beatschubser [brave/brave-browser#14473 (comment)](https://github.com/brave/brave-browser/issues/14473#issuecomment-791401507)

Actually that is not the solution ;) See my next post in the linked thread:

> Ok, it seems you have to whitelist the (Sub-)Domains for the failing addon-requests, in case of Pushbullet:
> @@*.pushbullet.com
> That is working fine. If you can't wait for the official fix, open the dev tools for the broken Addon, check the network-tab for blocked requests and add those to the whitelist.

**Comment by owl4ce** [comment]
Fixed in 
**Version 1.21.74 Chromium: 89.0.4389.72 (Official Build) unknown (64-bit)**

**Comment by subhra74** [comment]
@lightwarriah , till the youtube download issue is fix, please use XDM extension which should work

**Comment by lightwarriah** [comment]
In my case this issue still exists even in version 89.1.22.67.
But it's now fixed in the Brave Beta 89.1.23.48.
